version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: echo "building"
      - run:
          command: |
            cd app
            npm install
            npm run start
  test:
    docker:
      - image: cypress/browsers:chrome67
    steps:
      - checkout
      - run: echo "testing"
      - run:
          command: |
            cd app
            npm install
            npm run cy:run

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build
      - test:
          requires:
            - build # wait for build1 job to complete successfully before starting
            # see circleci.com/docs/2.0/workflows/ for more examples.
