version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "building"
      - run: cd app
      - run: npm install
      - run: npm run start
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "testing"
      - run: cd e2e
      - run: npm install
      - run: npm run cy:run

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build
      - test:
          requires:
            - build # wait for build1 job to complete successfully before starting
            # see circleci.com/docs/2.0/workflows/ for more examples.
